### ISSUE TITLE
_zQPSolveASM()とは？

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki-fd#23]
https://github.com/mi-lib/zm/issues/2#issue-1364819929
@n-wakisaka この件分かりますか？
_zQPSolveASM()という関数が定義されていない、というエラーです。

今ZMにあるzQPSolveASM()はRoKi-FDで使われることを前提にしている都合で、他のzQPSolve*()と違うAPIを持っているので、いっそのことこれはRoKi-FD専用関数にしようか、という話を以前にしたのと関連してるのかと予想してます。

**Comment by n-wakisaka** [comment]
エラーの原因は_zQPSolveASMは昔staticではなかったのですが，staticが付いたためroki-fdから参照できなくなったためみたいです．
使っている部分はこちらになります．
https://github.com/mi-lib/roki-fd/blob/7fb2ef03dc19a8b47ad067ceb2a2bc0fc8be9fb6/src/rkfd_vert.c#L250-L256

staticが付いたときのコミットdiffはこちらになります．
https://github.com/mi-lib/zm/commit/350e21a75ec2ae5a1ce83ea8f3e9463a6984619f#diff-c83a74677527f0953b191397dd960f37ccb03316ea5f438ee772a5e38cb8fde5R177 

ただ，_から始まる関数なので内部関数としてstaticを付けるほうが正しいと思います．

zQPSolveASMの引数を他の実装と合わせようとしたため，roki-fd側で拡張したい部分を_zQPSolveASMの引数にいれて使おうとした感じだったと思います．
現在はzQPSolveASMの引数に初期実行可能解を作るinit関数を引数に追加しているので他ともあっていませんが...

roki-fdで使う制約条件が摩擦の条件で行列で書くとかなり疎なので，制約が有効化確認する計算がボトルネックになっていたので展開した部分を関数ポインタにして入れるようになっています．

ぱっと思いつく改善案としては，
* _zQPSolveASMをなにか別名にしてpublicな関数にする
* zQPSolveASMの引数に_zQPSolveASMに入れているcondを追加する
あたりかなと思います．
ただ，init関数は使う側が設定したい状況もあると思いますが，cond関数は普通ないと思うので，通常の公開関数にcond関数が入っているのは微妙かなとも思いました．

**Comment by zhidao** [comment]
本件放置してしまってました。済みません。
とりあえず_zQPSolveASM()をZMからRoKi-FDに移し、RoKi-FDスペシフィックなものだと分かるように関数名を変えてもらうのが良いかと思っています。
今、汎用なzQPSolveASM()の実装をZMの方で試みています。逆に脇坂くんが作ってくれた方は、汎用性を無くしてくれて構いません。

**Comment by n-wakisaka** [comment]
確認ありがとうございます。それでは、_zQPSolveASM()部分まるっとroki-fd以下に複製してroki-fdではそちらを使うように変更しようと思います。

**Comment by zhidao** [comment]
こちらもcloseします。
