### ISSUE TITLE
rkCDChainReg()の第3引数？

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki-fd#30]
@n-wakisaka 
rkfd_sim.cの中の_rkFDCellPush()で、
```C
  rkCDChainReg( rkFDCDBase(&fd->cd), rkFDCellChain(lc), true );
```
という一文がありますが、rkCDChainReg()の第3引数はrkCDCellType（enum型）です。
trueということは1なので、とりあえずmi-lib/feature/lib_cppでは対応するRK_CD_CELL_MOVEを入れておきました。
```C
  rkCDChainReg( rkFDCDBase(&fd->cd), rkFDCellChain(lc), RK_CD_CELL_MOVE );
```
念のため元の文も残して#if 0～#endifで囲ってあります。

これで問題ないか確認お願いします。

**Comment by n-wakisaka** [comment]
@zhidao 
対応遅くなってすいません。
rkCDCellTypeを入れる場所にboolが入っているのはおかしいのでバグだと思います…

rkCDCellTypeの意味を忘れてしまったのですが、少しコードを見てみてRK_CD_CELL_STATは固定されたshape、RK_CD_CELL_MOVEは動きうるshapeという理解をしました。
理解が正しければ、rkfd_sim.cではRK_CD_CELL_MOVEで大丈夫なはずです。

結果としてtrueを入れているのと同じになりますが、型が間違えているのはよくないのでRK_CD_CELL_MOVEにして元のものを消しておいていただけると幸いです

**Comment by n-wakisaka** [comment]
こちら完了したのでcloseさせていただきます．
