### ISSUE TITLE
debug/qp_intに修正を加えたのですが

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki-fd#48]
なぜかPRが作れないので、僕が何か勘違いしているような気がしています。中身を見てもらえますか？ @n-wakisaka 
修正内容は、いくつかの変数の型をunsigned にしただけです。

**Comment by n-wakisaka** [comment]
こちら #44 でマージして削除されたブランチのようですので、改めて別名ブランチでpushしていただくか、可能でしたらマージ後のコミットにrebaseしてからforce pushしていただくとうまくいくと思います！

**Comment by zhidao** [comment]
@n-wakisaka 改めて中身を見たら既にmainに取り込まれているようなので、忘れてもらって構わなそうです。お騒がせしてすみません。僕の手元リポジトリからは削除しました。
